server:
  servlet:
    session:
      tracking-modes:
      - cookie
  port: 9000

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: member
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations:
  - classpath:mapper/**/*.xml